### ISSUE TITLE
Trouble sending the data from my main electron file to my React UI

### ISSUE THREAD

**Issue by DevSebas-Code** [pushy/pushy-electron#12]
Hi, i'm trying some code example from the electron docs,  specically in my case, to send data received from Pushy that's declared in my main Electron file  to my React UI.

So for this purpose I'm using ipcMain and IpcRenderer.

Main.ts (Electron file)
   ```
 Pushy.setNotificationListener((data: DataReceived) => {
      const {ipcMain} = require("electron")
      console.log('Data Sending: ', data);
      ipcMain.on('variable-request', function (event, arg) {
        console.log(arg) // arg return  ['somevar', 'anothervar'] 

        event.sender.send('variable-reply', [data]); 
      });
      const auxData = JSON.stringify(data);
      // Display an alert with the "message" payload value
      Pushy.alert(mainWindow, 'Received notification: ' + auxData);
    });
```
renderer.tsx

```
const ipcRendererExec = () => {
  const ipcRenderer = window.require("electron").ipcRenderer;
  setInterval(() => {
    console.log("executing ipcRenderer  ")
    ipcRenderer.send('variable-request', ['somevar', 'anothervar']);

**//  ['somevar', 'anothervar'] are being received in mi main electron file**
    
    ipcRenderer.on('variable-reply', function (event, args) {
      console.log("REPLY: ", args) // args returns undefined here
    });

    console.log("After Function oooo")
  }, 5000)
}

ipcRendererExec()
// Say something
console.log('[ERWT] : Renderer execution started');

// Application to Render
const app = (
  <Provider store={store}>
    <Wrapper>
      <Application title='hola' version='1.0'  />
    </Wrapper>
  </Provider>
);

```
So basically, my error is that the args in my ipcRenderer in the event `"variable-reply"`, is returning `undefined`, so basically my data from pushy is not getting to the front-end 

I don't know if maybe the method     ` event.sender.send('variable-reply', [data]);` isn't being used correctly,? or maybe this another method : 

```
 ipcRenderer.on('variable-reply', function (event, args) {
       console.log("args: ", args)
    });
```

If someone could help me with issue, I'll be very thankful.

**Regards**

**Comment by pushy** [comment]
Hi @DevSebas-Code,
We'd be glad to assist.

It may indeed have to do with passing an array as the second parameter of `event.sender.send()`. Please pass the `data` object directly, or stringify the JSON into a string by calling `JSON.stringify(data)` and passing that.

You may use the following tutorial as a helpful guide on inter-process communication in Electron:
https://www.tutorialspoint.com/electron/electron_inter_process_communication.htm

Please let us know if you face any further difficulties.
